### ISSUE TITLE
get_phases_dataframe truncates milliseconds from arrival times

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/libcomcat#94]
Appears to be when creating phase_row:
https://github.com/usgs/libcomcat/blob/master/libcomcat/utils.py#L201

**Comment by jmfee-usgs** [comment]
It looks like `pick.time` should be an obspy UTCDateTime object at that point, is there a reason to create a python datetime and not use the obspy UTCDateTime?

**Comment by mhearne-usgs** [comment]
It was also getting truncated on write to Excel format, so I had to do some footwork to allow fractional seconds there.  I'm using datetime because I wasn't sure pandas would know what to do with the obspy UTCDateTime object, and I know it knows about datetime objects.  This was addressed with PR #95
